# -*- coding: utf-8 -*-
"""Greetingapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CrG1ytuPm67BE74xu6OQKFNpyJTDKcwc
"""

import streamlit as st
")st.title
رادار المشاعر المطور
gender = st.radio)"هل أنت", "ولد", "بنت"((
status = st.selectbox )"بماذا تشعر الآن؟" ("سعيد", "حزين", "بردان((
: ("! اكتشف شكلك") if st.button
if status == "سعيد" :
احتفال بالبالونات # ()st.balloons
"إيا له من يوم رائع ) st.success
elif status == "حزين" :
"إلا تحزن، غداً سيكون أفضل")st.info
elif status == "بردان":
تأثير الثلج السحري # ()st.snow
