# -*- coding: utf-8 -*-
"""Greetingapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CrG1ytuPm67BE74xu6OQKFNpyJTDKcwc

https://colab.research.google.com/drive/1jdOhpFP11Rgrx1BeN-poUh3M6e5faP1D?usp=sharing

